linters:
  rubocop:
<<<<<<< HEAD
    display_cop_names: true
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
=======
    fixer: true
  csslint: {  }
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
fixers:
  enable: true
>>>>>>> ffafbd39edef61682a89f7e88344698aab36f89c
